### ISSUE TITLE
undefined method `join' for nil:NilClass

### ISSUE THREAD

**Issue by sjaensch** [sharplet/minimal-swift#2]
After cloning the repository, any rake command (besides rake clean) aborts with this error:

    $ rake test
    mkdir -p build
    rake aborted!
    undefined method `join' for nil:NilClass
    /Users/sj/minimal-swift/Rakefile:7:in `block in <top (required)>'
    Tasks: TOP => test => build/runtests => build/libFoobar.a
    (See full trace by running task with --trace)

I'm on OS X 10.11.2 with Xcode 7.2. Unfortunately I have no idea about Ruby. :)

**Comment by sharplet** [comment]
That's pretty odd, I'm also on OS X 10.11.2 with Xcode 7.2, and I can't reproduce that bug.

Can you show me the output of `ruby -v`?

**Comment by sjaensch** [comment]
$ ruby -v
    ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    $ type ruby
    ruby is /usr/bin/ruby
    $ rake --version
    rake, version 0.9.6
    $ type rake
    rake is /usr/bin/rake

**Comment by sharplet** [comment]
Yeah, seems to be a problem on that version of rake. For some reason the `Task#sources` method is returning `nil`.

Can you try updating rake? It's gotten a little trickier to install gems on El Capitan, but this Stack Overflow answer explains things: http://stackoverflow.com/a/32253142.

It might be worth me trying to get this to work on 0.9.4 anyway.

**Comment by sharplet** [comment]
Unfortunately, even after working around the rake 0.9.4 issue, loading the test binary with Apple's xctest doesn't seem to work anymore under Xcode 7.2. I'm not sure why, or when this changed :(

However I think the Swift Package Manager and swift-corelibs-xctest should be the way to do this stuff in the future, so that's what I'd recommend looking into now.

Going to close this issue, but let me know if you have any other questions.

**Comment by sharplet** [comment]
Just FYI, I've updated the readme with this advice. https://github.com/sharplet/minimal-swift/commit/c215adf6f108d218e7b13760487eb81ddad0854e
